---
context: k8s.prod.mydomain.com
global:
  globalVar: lizards
include:
  # By default resource sets are included from a folder with the same
  # name as the resource set's name
  - name: some-api
    values:
      version: 1.0-0e6884d
      importantFeature: true
      apiPort: 4567

  # Paths can also be specified manually (and point at single template
  # files!)
  - name: other-config
    path: other-config.yaml
