---
language: nix
script:
  # Build the derivation targeting NixOS.
  # This derivation executes tests.
  - nix-build default.nix

  # Build the release derivation with statically linked executables
  # for multiple operating systems.
  - nix-build release.nix
